/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAffix: typeof import('ant-design-vue/es')['Affix']
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABackTop: typeof import('ant-design-vue/es')['BackTop']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACardGrid: typeof import('ant-design-vue/es')['CardGrid']
    ACardMeta: typeof import('ant-design-vue/es')['CardMeta']
    ACol: typeof import('ant-design-vue/es')['Col']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AFloatButton: typeof import('ant-design-vue/es')['FloatButton']
    AFloatButtonGroup: typeof import('ant-design-vue/es')['FloatButtonGroup']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AListItemMeta: typeof import('ant-design-vue/es')['ListItemMeta']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    APageHeader: typeof import('ant-design-vue/es')['PageHeader']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    AStatistic: typeof import('ant-design-vue/es')['Statistic']
    ATypographyParagraph: typeof import('ant-design-vue/es')['TypographyParagraph']
    Banner: typeof import('./src/components/content/BannerBar.vue')['default']
    BannerBar: typeof import('./src/components/content/BannerBar.vue')['default']
    Content: typeof import('./src/components/Content.vue')['default']
    FlexworkBar: typeof import('./src/components/content/FlexworkBar.vue')['default']
    FooterBar: typeof import('./src/components/FooterBar.vue')['default']
    GlobalSideBar: typeof import('./src/components/GlobalSideBar.vue')['default']
    HonorBar: typeof import('./src/components/content/HonorBar.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    News: typeof import('./src/components/content/NewsBar.vue')['default']
    NewsBar: typeof import('./src/components/content/NewsBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SolutionBar: typeof import('./src/components/content/SolutionBar.vue')['default']
    StatisticsBar: typeof import('./src/components/content/StatisticsBar.vue')['default']
    TalentServiceBar: typeof import('./src/components/content/TalentServiceBar.vue')['default']
    VideoBar: typeof import('./src/components/content/VideoBar.vue')['default']
  }
}
